### PR TITLE
Tags related to a scenario are shown by the scenario similarly to fea…

### PR DESCRIPTION
**Pull request by tom-metz**
There can be tags defined at the scenario level, not only top by the feature. This PR is adding these tags into the default HTML template.

### CODE REVIEW

**Comment by leinonen** [comment]
Thanks

**Comment by tom-metz** [comment]
You're welcome. I have one more improvement in preparation: being able to define the name of the output HTML file. We need one report per cappability. Is it OK for you?

**Comment by leinonen** [comment]
There was another pull request for that by some other guy, but you can fix
it if you like. :)

**Comment by tom-metz** [comment]
There was something wrongwith the previous PR?

Anyway, I wanted to ask for help with additional feature, if you don't mind. It would be helpful to visualy see, which tags were really used - so those, which were given to cucumber via "cucumberOpts.tags". Unfortunately, I wasn't able to find a way, how to grt them properly. The issue is, that the tags can be given as parameter to cucumber or in the Protractor configuration file. Cucumber merges them, but it looks like, it does not expose them. Or I am unable to find how. Any idea? I have no problem to implement it to the report, but being stuck at the moment :-(

**Pull request merged**
