### PR TITLE
Template renderer added and templatet extended with tables and charts…

### PR DESCRIPTION
**Pull request by richardpap**
… and screenshots

### CODE REVIEW

**Comment by leinonen** [comment]
Why did you close it?

**Comment by richardpap** [comment]
Some of the tests have failed. After the fixes, i'm gonna reopen it :)

**Comment by leinonen** [comment]
Looking forward to it :)

**Comment by richardpap** [comment]
I've reopened the PR. One test have failed here somehow, its strange, cuz the last commit is the fix for that issue. A lots of things have changed in this branch, please take a look, and merge it if you like it.

**Comment by leinonen** [comment]
I really like what you have done, but there are some issues we must resolve.

1. Fix the tests

The following code causes the promise to reject with true.
I think it is a timing issue or something, because the directory does get created.

template_builder.js:56
```javascript
if(self.checkOptions(self.report.options) !== true) {
  reject(self.checkOptions(self.report.options));
}
```

2. index.js should be the entrypoint of the report generator.

3. Update README.md with a working usage example.

4. If you have a cucumber.json file with many features (100 or more) and steps, then the generated html becomes quite large because of the stepCharts. There should be an option to include stepCharts, perhaps with a default of true. But i really like the feature :)

5. If no option for screenshots is provided, it should still run.

5. I like the print report button, but we need some kind of print stylesheet to make it look better, perhaps remove the sidebar, or just display the summary at the top of the page.

**Comment by richardpap** [comment]
Hey. Sounds good. I'm gonna make the changes, and let you know when it's done.

**Comment by richardpap** [comment]
I've fixed the timing issue with the directory creating. Now all the tests passed successfully. Rest is incoming soon :)

**Comment by leinonen** [comment]
I will merge this when all things are in place. Take your time.

**Comment by richardpap** [comment]
By "index.js should be the entrypoint of the report generator" what do you mean exactly? Now the app can be started by running index.js in the root folder.

**Comment by richardpap** [comment]
Oh, nice. I'm making a commit also with the updated README.md file.

**Comment by leinonen** [comment]
Please do :)

**Pull request merged**
