### PR TITLE
Issue #25 -- datatables

### PR DESCRIPTION
**Pull request by leegee**

### CODE REVIEW

**Comment by leegee** [comment]
Lacks tests, I'm afraid, but it's only a little bit of mustache

**Comment by leinonen** [comment]
Cool. If you have some example json files you can share, I would like that. I was thinking of having an examples folder with different json files that you can use when testing the report generator.

**Comment by leegee** [comment]
I've put a couple of samples in `samples/`, which is probably not a great place for them, but at least it will give you the data.

**Comment by leegee** [comment]
https://github.com/leinonen/cucumber-html-report/pull/29

**Pull request merged**
